version: '3'
services:
  location-api:
    container_name: location-api
    build: .
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - db
    links:
      - db
    networks:
      - compose-network

  db:
    container_name: db
    restart: always
    image: postgres
    ports:
      - 5432:5432
    env_file: db.env
    networks:
      - compose-network

networks:
  compose-network:
    driver: bridge
